### ISSUE TITLE
Social Network Extraction for Amazon Dataset

### ISSUE THREAD

**Issue by shashankg7** [Linda-sunshine/HUB#1]
Hi, 

How are you constructing the social Network structure of the users in the Amazon Dataset? 

I checked the dataset page, the Metadata section has a "co-purchase" field. Are you using that field? If yes, then can you please elaborate on how?

**Comment by Linda-sunshine** [comment]
I directly looked into each user's purchased items among the sampled user set. If two users purchased the same item, they will be considered as friends.

**Comment by shashankg7** [comment]
Thanks a lot for your reply. This answers my question.
